spring.application.name=vitrina-productos

# 1. Conexión a tu base de datos PostgreSQL (Neon)
# Nota: Se le agrega "jdbc:" al principio de la URL que me pasaste
spring.datasource.url=jdbc:postgresql://ep-mute-math-and92wz7-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ZBM0xlesyIu5
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de Hibernate y JPA
# ¡OJO! Está en 'create' para limpiar y crear las tablas (OPCIÓN B). 
# Recuerda cambiarlo a 'update' después de arrancar la app por primera vez.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# 3. Logs para ver la magia de SQL en consola
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE