spring.application.name=vitrina-productos

spring.config.import=optional:file:.env

# 1. Conexión a tu base de datos PostgreSQL (Neon)
# Nota: Se le agrega "jdbc:" al principio de la URL que me pasaste
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de Hibernate y JPA
# ¡OJO! Está en 'create' para limpiar y crear las tablas (OPCIÓN B). 
# Recuerda cambiarlo a 'update' después de arrancar la app por primera vez.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

cloudinary.cloud-name=victor
cloudinary.api-key=797338976491989
cloudinary.api-secret=dA6D8XiNqz3rimXNKasIzTEyDWs

# 3. Logs para ver la magia de SQL en consola
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE